const { validationResult } = require('express-validator/check')
const validation = require('../helpers/validation')
const { ValidationError } = require('../errors/apiErrors/apiErrors')

/**
 * Sends validation errors generated by express-validator.
 * Should be placed right after all validation middleware.
 */
module.exports = () => (req, res, next) => {
  const errors = validationResult(req)

  if (!errors.isEmpty()) {
    return next(new ValidationError(...validation.spreadErrors(errors.mapped())))
  }

  next()
}
